// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgayhtNl3ED4_9_h0J6vu9tt_GTId8bvw',
    appId: '1:317225981921:web:94b0a7df3068ffeda864a0',
    messagingSenderId: '317225981921',
    projectId: 'myyt-78fad',
    authDomain: 'myyt-78fad.firebaseapp.com',
    storageBucket: 'myyt-78fad.appspot.com',
    measurementId: 'G-G5XMHTJJNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRGPG9_tmVcue7FxD8hxS7KZyQnpkdXL8',
    appId: '1:317225981921:android:6a7385ab7065a8a3a864a0',
    messagingSenderId: '317225981921',
    projectId: 'myyt-78fad',
    storageBucket: 'myyt-78fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSv-DPVjQmFIXnJgP5doiHkGM4yroEmyk',
    appId: '1:317225981921:ios:76b7054b779e0e17a864a0',
    messagingSenderId: '317225981921',
    projectId: 'myyt-78fad',
    storageBucket: 'myyt-78fad.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSv-DPVjQmFIXnJgP5doiHkGM4yroEmyk',
    appId: '1:317225981921:ios:76b7054b779e0e17a864a0',
    messagingSenderId: '317225981921',
    projectId: 'myyt-78fad',
    storageBucket: 'myyt-78fad.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgayhtNl3ED4_9_h0J6vu9tt_GTId8bvw',
    appId: '1:317225981921:web:47613421676d893ea864a0',
    messagingSenderId: '317225981921',
    projectId: 'myyt-78fad',
    authDomain: 'myyt-78fad.firebaseapp.com',
    storageBucket: 'myyt-78fad.appspot.com',
    measurementId: 'G-3R1VZ3P02X',
  );
}
